console.log(`Котик > котик: ${"Котик">"котик"}`);
console.log(`Котик > китик:${"Котик">"китик"}`);
console.log(`Кот > котик: ${"Кот">"котик"}`);
console.log(`Привет > Пока: ${"Привет">"Пока"}`);
console.log(`73 > "53": ${73>53}`);
console.log(`false < 0.54: ${false<0.54}`);
console.log(`true < 0.54: ${true<0.54}`);
console.log(`false < true: ${false<true}`);
console.log(`123 < false: ${123<false}`);
console.log(`true < "3": ${true<"3"}`);
console.log(`3 < 5mm: ${3<"5mm"}`);
console.log(`8>"-2": ${8>"-2"}`);
console.log(`34 == "34": ${34=="34"}`);
console.log(`null=undenfined: ${null==undefined}`);